# Generated by Django 4.0.4 on 2022-04-21 05:35

from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=100, verbose_name='Street')),
                ('house', models.CharField(blank=True, max_length=15, verbose_name='House')),
                ('structure', models.CharField(blank=True, max_length=10, verbose_name='Корпус')),
                ('building', models.CharField(blank=True, max_length=10, verbose_name='building')),
                ('apartment', models.CharField(blank=True, max_length=10, verbose_name='Кв/Оф')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='location.city', verbose_name='City')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='location.region', verbose_name='Region')),
            ],
            options={
                'verbose_name': 'user contacts',
                'verbose_name_plural': 'list of user contacts',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=58, verbose_name="shop's name")),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('order_accepting', models.BooleanField(default=True, help_text="indicates the shop's ability to accept orders", verbose_name='order receving status')),
            ],
        ),
        migrations.CreateModel(
            name='ShopDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivered_price', models.PositiveIntegerField(verbose_name='Delivery price')),
                ('quantity', models.PositiveIntegerField(help_text='Min quantity for price delivery', verbose_name='Quantity')),
                ('shop', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_deliverys', to='accounts.shop', verbose_name='shop')),
            ],
            options={
                'verbose_name': 'shop delivered',
                'verbose_name_plural': 'list of shop delivery',
            },
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ('email',), 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Список пользователей'},
        ),
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='customuser',
            name='company',
            field=models.CharField(blank=True, max_length=100, verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_admin',
            field=models.BooleanField(default=False, help_text='Indicates that the user is superuser', verbose_name='Admin'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='position',
            field=models.CharField(blank=True, max_length=100, verbose_name='position'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='type',
            field=models.CharField(choices=[('shop', 'Магазин'), ('buyer', 'Покупатель')], default='buyer', help_text='choose your role in  between   shop and buyer', max_length=5, verbose_name='user type'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email adres'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indicates that the user can use the accountUnselect this instead of deleting accounts', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with this name already exist'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='user name'),
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
        migrations.AddField(
            model_name='shop',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='contact',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddConstraint(
            model_name='shopdelivery',
            constraint=models.UniqueConstraint(fields=('shop', 'quantity'), name='unique_shop_delivery'),
        ),
    ]
