# Generated by Django 4.0.4 on 2022-05-06 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_shop_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(default='+7 (999) 999-99-99', max_length=20, verbose_name='phone number'),
            preserve_default=False,
        ),
    ]
