# Generated by Django 4.0.4 on 2022-05-05 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='cost_one',
            field=models.FloatField(blank=True, help_text='cost for one position', null=True, verbose_name='cost'),
        ),
    ]
