# Generated by Django 4.0.4 on 2022-05-18 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_orderitem_cost_one'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercost',
            name='order',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_cost', to='order.order', verbose_name='Order'),
        ),
    ]
