# Generated by Django 4.0.4 on 2022-04-21 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_contact_shop_shopdelivery_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=58, verbose_name="Category's name")),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'List category',
                'ordering': ('-name',),
            },
        ),
        migrations.CreateModel(
            name='CategoryShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_shops', to='category.category', verbose_name='Category')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_shops', to='accounts.shop', verbose_name='Shop')),
            ],
            options={
                'ordering': ('-shop',),
            },
        ),
        migrations.AddConstraint(
            model_name='categoryshop',
            constraint=models.UniqueConstraint(fields=('shop', 'category'), name='unique_category_info'),
        ),
    ]
